
services: 

    redis:
        image: redis:7.0.11-alpine
        
    django:
        container_name: django
        build:
            context: ./learn_celery
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./learn_celery:/usr/src/app/
        ports:
            - 8001:8000
        environment:
            - DEBUG=1
            - SECRET_KEY=Athebby65ggrtyver45grvrgrr
            - ALLOWED_HOSTS=localhost, 127.0.0.1

        depends_on:
            - redis

    celery:
        container_name: celery
        build:
            context: ./learn_celery
        command: celery --app=learn_celery worker -l INFO
        volumes:
            - ./learn_celery:/usr/src/app/
        environment:
            - DEBUG=1
            - SECRET_KEY=Athebby65ggrtyver45grvrgrr
            - ALLOWED_HOSTS=localhost, 127.0.0.1

        depends_on:
            - redis